---
name: MP3-M3U-Parser
version: 2.23
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: MP3 playlist parser.
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-mp3-m3u-parser/
requires:
  Cwd: 0
  File::Spec: 0
  IO::File: 0
  Text::Template: 0
build_requires:
  Test::More: 0.40
provides:
  MP3::M3U::Parser:
    file: lib/MP3/M3U/Parser.pm
    version: 2.23
  MP3::M3U::Parser::Dummy:
    file: lib/MP3/M3U/Parser.pm
no_index:
  directory:
    - monolithic_version
    - builder
    - t
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
