---
name: MP3-M3U-Parser
version: 2.21
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: MP3 playlist parser.
license: perl
resources:
  license: ~
requires:
  Cwd: 0
  File::Spec: 0
  IO::File: 0
  Test::More: 0.40
  Text::Template: 0
provides:
  MP3::M3U::Parser:
    file: lib/MP3/M3U/Parser.pm
    version: 2.21
  MP3::M3U::Parser::Dummy:
    file: lib/MP3/M3U/Parser.pm
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
