# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         MP3-M3U-Parser
version:      2.0
version_from: lib/MP3/M3U/Parser.pm
installdirs:  site
requires:
    Cwd:                           0
    File::Spec:                    0
    IO::File:                      0
    Text::Template:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
